// <auto-generated />
using KaraokeList.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KaraokeList.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250602120000_AddApplicationUserSingerId")]
    partial class AddApplicationUserSingerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Target model is defined in ApplicationDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
