param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectPath,
    [Parameter(Mandatory = $true)]
    [string]$CodegenPath,
    [string]$SyncfusionKey
)

$ErrorActionPreference = 'Stop'

function Get-SyncfusionKeyFromUserSecrets {
    param([string]$Path)
    $list = & dotnet user-secrets list --project $Path 2>$null
    if (-not $list) { return $null }
    foreach ($line in $list) {
        if ($line -match '^SyncfusionKey\s*=\s*(.+)$') {
            return $Matches[1].Trim()
        }
    }
    return $null
}

$key = $SyncfusionKey
if ([string]::IsNullOrWhiteSpace($key)) {
    $key = Get-SyncfusionKeyFromUserSecrets -Path $ProjectPath
}

$escaped = if ([string]::IsNullOrWhiteSpace($key)) {
    $null
} else {
    $key.Trim().Replace('\', '\\').Replace('"', '\"')
}

$valueLine = if ($null -eq $escaped) {
    '    internal const string? Value = null;'
} else {
    "    internal const string? Value = `"$escaped`";"
}

$content = @"
// <auto-generated> From user secrets at build time. Do not commit.</auto-generated>
#nullable enable
namespace KaraokeList.Web;

internal static class SyncfusionLicenseKey
{
$valueLine
}
"@

Set-Content -Path $CodegenPath -Value $content.TrimEnd() -Encoding utf8
exit 0
